# Generated by Django 3.1.2 on 2020-11-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='almohada',
            fields=[
                ('id_almohada', models.AutoField(db_column='id_alumno', primary_key=True, serialize=False)),
                ('nombre_almohada', models.CharField(blank=True, max_length=20, null=True)),
                ('medida', models.CharField(blank=True, max_length=20, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='daikimakura',
            fields=[
                ('id_daiki', models.AutoField(db_column='id_alumno', primary_key=True, serialize=False)),
                ('nombre_daiki', models.CharField(blank=True, max_length=20, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='peluche',
            fields=[
                ('id_peluche', models.AutoField(db_column='id_alumno', primary_key=True, serialize=False)),
                ('nombre_peluche', models.CharField(blank=True, max_length=20, null=True)),
                ('medida', models.CharField(blank=True, max_length=20, unique=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('tamaño', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
