# Generated by Django 3.1.2 on 2020-11-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peluche',
            name='medida',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
