# Generated by Django 3.1.2 on 2020-11-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20201102_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peluche',
            old_name='tamaño',
            new_name='tamano',
        ),
    ]
