# Generated by Django 3.1.2 on 2020-11-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20201102_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='almohada',
            name='id_almohada',
            field=models.AutoField(db_column='id_almohada', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='daikimakura',
            name='id_daiki',
            field=models.AutoField(db_column='id_daikimakura', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='peluche',
            name='id_peluche',
            field=models.AutoField(db_column='id_peluche', primary_key=True, serialize=False),
        ),
    ]
